<a href="https://colab.research.google.com/github/jainxy/numpy_tutpt/blob/master/Array%20Manipulation_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array Manipulation
__(https://www.tutorialspoint.com/numpy/numpy_array_manipulation.htm)__
Numpy package provides several routines for manipulating elements in ndarray objects.

### Changing shape
1. __reshape()__ -> __(https://www.tutorialspoint.com/numpy/numpy_reshape.htm)__ 
Gives new shape to an array w/o tweaking its data
1. __flat__ -> __(https://www.tutorialspoint.com/numpy/numpy_ndarray_flat.htm)__
Returna a 1-D iterator over the array. similar to python's built-in iterator.
1. __flatten()__ -> __(https://www.tutorialspoint.com/numpy/numpy_ndarray_flatten.htm)__
returns __copy__ of an array, collapsed into 1-D.
1. __ravel()__ -> __(https://www.tutorialspoint.com/numpy/numpy_ndarray_ravel.htm)__
returns a flattened 1-D array. A copy is made only if needed. 

In [0]:
import numpy as np

In [0]:
# reshape() and flat
a = np.arange(8).reshape(2,4) 
itr = a.flat
print(itr[5])  # Returns element at index 5 in flattened array.

5


In [0]:
# flatten()
print("ID of original array - {}".format(id(a)))

a_flatten_C = a.flatten(order='C')
print("ID of Flattened row-major array - {}".format(id(a_flatten_C)))
print(a_flatten_C)

a_flatten_F = a.flatten(order='C')
print("ID of Flattened col-major array - {}".format(id(a_flatten_F)))
print(a_flatten_F)

ID of original array - 95528000
ID of Flattened row-major array - 95530880
[0 1 2 3 4 5 6 7]
ID of Flattened col-major array - 95530400
[0 1 2 3 4 5 6 7]


In [0]:
# ravel()
print("ID of original array - {}".format(id(a)))

a_ravel_C = a.ravel(order='C')
print("ID of Flattened row-major array - {}".format(id(a_ravel_C)))
print(a_ravel_C)

a_ravel_F = a.ravel(order='C')
print("ID of Flattened col-major array - {}".format(id(a_ravel_F)))
print(a_ravel_F)

ID of original array - 95528000
ID of Flattened row-major array - 95552096
[0 1 2 3 4 5 6 7]
ID of Flattened col-major array - 95552496
[0 1 2 3 4 5 6 7]


### Transpose Operations
1. __transpose()__ -> __(https://www.tutorialspoint.com/numpy/numpy_transpose.htm)__ 
Permutes the dimension of the given array. Returns a __view__ wherever possible.
1. __ndarray.T__ -> __(https://www.tutorialspoint.com/numpy/numpy_ndarray_t.htm)__
Same as transpose()
1. __rollaxis()__ -> __(https://www.tutorialspoint.com/numpy/numpy_rollaxis.htm)__
function rolls the specified axis backwards, until it lies in a specified position. The function takes three parameters.
1. __swapaxes()__ -> __(https://www.tutorialspoint.com/numpy/numpy_swapaxes.htm)__
interchanges 2 axes of an array. Returns a __view__ of swapped array.

In [0]:
import numpy as np

In [0]:
# transpose(axes) -> axes: list of ints corresp to dims. By default, dims are reversed.
# reshape() and flat
a = np.arange(8).reshape(2,4) 

print("ID of original array - {}".format(id(a)))
print("Shape - {}".format(a.shape))

a_transpose = a.transpose()
print("ID of transposed array - {}".format(id(a_transpose)))
print("Shape - {}".format(a_transpose.shape))
print(a_transpose)

a_transpose_2 = a.T
print("ID of transposed array - {}".format(id(a_transpose_2)))
print("Shape - {}".format(a_transpose_2.shape))
print(a_transpose_2)

ID of original array - 93149984
Shape - (2, 4)
ID of transposed array - 95555136
Shape - (4, 2)
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
ID of transposed array - 95554816
Shape - (4, 2)
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [0]:
# TBD
# rollaxis(axis, start) -> axis: Axis to roll backwards; start: 

In [0]:
# swapaxes(axis1, axis2) -> Interchanges 2 axes

a = np.arange(8).reshape(2,2,2) 
print("ID of original array - {}".format(id(a)))
print("Original array - \n{}".format(a))

a_swapaxes = a.swapaxes(0,1)
print("ID of original array - {}".format(id(a_swapaxes)))
print("Original array - \n{}".format(a_swapaxes))

ID of original array - 95564384
Original array - 
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
ID of original array - 95564304
Original array - 
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
