## Indexing and Slicing
__(https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm)__

- We can access and modify the contents/ements of ndarray objects, just like python's built-in container object, via indexing and slicing.
- ndarray objects follow zero-based index.
- 3 types of indexing methods ->
    - Field access
    - base slicing
    - advanced indexing

### Basic python slicing
slice a given sequence (string, bytes, tuple, list or range) or any object which supports sequence protocol (implements ```__getitem__()``` and ```__len__()``` methods).
1. slicing operator -> __```[start:stop:step]```__

    It gives list of indices, beginning from _start_, with limit at _stop_, incrementing in _step_.
    -ve step means traversal in reverse direction.

2. __slice()__ function -> creates a __slice object__ represnting set of indices, specified by __```range(start=0,stop,step=1)```__. pass it as array index to extract a part of array.

In [2]:
import numpy as np
ndarr = np.array([x*10 for x in range(2,10)])
ndarr_s = ndarr[slice(1,6,2)]
print(ndarr_s)

[30 50 70]


In [4]:
# direct slicing of ndarray
ndarr = np.array([x*10 for x in range(2,10)])
print(ndarr[1:6:2])
print(ndarr[1:])
print(ndarr[:3])   # stop index is not included
print(ndarr[1:3])  # stop index is not included

[30 50 70]
[30 40 50 60 70 80 90]
[20 30 40]
[30 40]


In [23]:
# Multi-dim array slicing
ndarray2 = np.array([[ 1,  2,  3,  4],
                       [ 5,  6,  7,  8],
                       [ 9, 10, 11, 12],
                       [13, 14, 15, 16]])
# we slice along both the dimentions
print(ndarray2[1:,:3])
print(ndarray2[:,1:3])
print(ndarray2[slice(1,-1),slice(-1)])
print(ndarray2[... , slice(-1)])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


ellipsis (...) can be used to make a selection tuple of same length as # of dim of array. for any axis, ... means :, i.e. all the indices in that axis.

In [35]:
ndarray2 = np.array([[1,2,3],[3,4,5],[4,7,6]])
print(ndarray2)
print(ndarray2[...,1]) # print 2nd column only
print(ndarray2[1,...]) # print 2nd row only

[[1 2 3]
 [3 4 5]
 [4 7 6]]
[2 4 7]
[3 4 5]


## Advanced indexing
__(https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm)__
 - We can make selection from ndarray object.
 - Two types of advanced indexing -> __Integar__ and __Boolean__
 
1. __Integer Indexing__ -> Select any arbitrary item in an array based on its Ndimentional index. Each integer array represent indexes in that dimention.
2. __Boolean Indexing__ -> This type of Advanced indexing is used when we need to obtain resultant object as a result of Boolean operations. Like boolean operators (>, <, etc)

In [37]:
import numpy as np

In [40]:
ndarray2 = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray2[[0,1,2],[0,1,0]])
print(ndarray2[:,[0,1,0]])  # combination of basic-indexing with advanced-indexing(for column)

[1 4 5]
[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [41]:
# select corners from 4x3 matrices as 2D ndarray
ndarray2 = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
print(ndarray2[rows,cols])

[[ 0  2]
 [ 9 11]]


In [42]:
# Boolean Indexing
ndarray2 = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
ndarray_bool = ndarray2[ndarray2>5]
print(ndarray_bool)

[ 6  7  8  9 10 11]


In [51]:
# np.nan ; np.isnan() ; ~ operator
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

# np.iscomplex()
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]


## Broadcasting
__(https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)__
 - broadcasting means to bring ndarrays of different shapes/dimentions to common shape during arithmetic operations.
 - Arithmetic operations on arrays are performed on the corresponding elements. If dimensions of 2 arrays are not similar, smaller array is broadcasted to the size of the larger array, to get similar shape.
 - __Rules for broadcasting__ to be possible :-
     1. Array with smaller __ndim__ than the other is __prepended__ with __'1'__ in its shape.
     2. For each dim, output size is maximum of input sizes.
     3. An input can be used in Arithmetic operation, if its size in all dims is either same as output size or '1'.
     4. If an input has a dim size of 1, the 1st data entry in that dim is used for all the calculation along that dim.

In [52]:
import numpy as np

In [53]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) # it will be broadcated to match shape of a
print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## Iterating over array
__(https://www.tutorialspoint.com/numpy/numpy_iterating_over_array.htm)__
 - Numpy provides an iterator object - __numpy.nditer__
 - Its an efficient multi-dim array, to visit each element of an array using Python's iterator interface.
 - The order of iteration is chosen to match the memory layout of an array
 - We can force __nditer__ object to follow a specific order by using parameter _'order'_ which can take _'F'/'C'/'A'_
 - *op_flags* parameter which is list of list of flags, can be used for setting attribute for iterator on arrays.
 - If 2 arrays are broadcastible, a combined __nditer__ object can be created to iterate upon them simultaneously.

In [63]:
import numpy as np

In [67]:
arr3x4 = np.arange(0,60,5).reshape(3,4)
print(arr3x4)

for val in np.nditer(arr3x4):
    print(val,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [68]:
# order of teration is as per memory layout
arr3x4 = np.arange(0,60,5).reshape(3,4)
arr3x4_T = arr3x4.T
print(arr3x4_T)

for val in np.nditer(arr3x4_T):
    print(val,end=' ')

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [70]:
# Elements stored in F-style order, then iterator moves in that order.
arr3x4 = np.arange(0,60,5).reshape(3,4)
arr3x4_F = arr3x4.copy(order='F')
print(arr3x4_F)

for val in np.nditer(arr3x4_F):
    print(val,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

In [82]:
# set op_flags to mark array as readwrite while iterating over it.
arr3x4 = np.arange(0,60,5).reshape(3,4)
print(arr3x4)

for val in np.nditer(arr3x4,op_flags=['writeonly']):
    val[...] = 2*val
print(arr3x4)
print(type(val))

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
<class 'numpy.ndarray'>


In [90]:
arr3x4 = np.arange(0,60,5).reshape(3,4)
arr3x1 = np.array([1,2,3]).reshape(3,1)
print(arr3x4)
print(arr3x1)

for val1,val2 in np.nditer([arr3x4,arr3x1]):
    print("{}-{}".format(val1,val2), end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[1]
 [2]
 [3]]
0-1 5-1 10-1 15-1 20-2 25-2 30-2 35-2 40-3 45-3 50-3 55-3 