## Introduction
(https://www.tutorialspoint.com/numpy/numpy_introduction.htm)
- Numpy means "Numerical Python" library
- Has multi-dim array objects and APIs to process those MD objects
- With it, we can perform arithmatic and logical operations on arrays
- Other operations like indexing, slicing, broadcasting etc.
- Native support with other sister libs for extending usecases like,
    - Scipy for Image operations, and other scientific algos in python
    - Matplotlib for plotting and graphing
    - Panda for buiding dataframes and relared operations
    - Scikit-learn for representing its tensors in ML usecases
- It is widely used for Linear algebra as basic data unit is MDim array there
- Scipy+Numpy+Matplotlib can effectively replcace Matlab,
    - Numpy provide Matrix computation backbone
    - Scipy provides algos
    - Matplotlib provides rich plotting functionality
    - Scipy stack : Numpy+scipy+Ipython+Matplotlib+sympy+core-python


## Ndarray objects
(https://www.tutorialspoint.com/numpy/numpy_ndarray_object.htm)
- N-dimentional array, called "_ndarray_"
- It defines collection of objects of same type, which can be accessed with indexing
- Each element is an object of data-type object, called "_dtype_"
- We can extract subset of elements via "_slicing_", to get python object of array-scalar type.
- It contains of contigous 1-D memory, along with indexing scheme to map each item to a location in memory block.
- By default, memory block has elements in row-major order

### Creating Ndarray objects
```python
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

In [10]:
import numpy as np
a = np.array([1,2,3,4], ndmin=2)  # minimum dim as 2
print(a.shape)

(1, 4)


In [13]:
arr_com = np.array([1,2,3,4], ndmin = 2, dtype = complex) # Data-type of elements is coplex
print(arr_com)
print("Shape : {}".format(arr_com.shape))

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j]]
Shape : (1, 4)


## Numpy data-types (dtype)
(https://www.tutorialspoint.com/numpy/numpy_data_types.htm)
- Numpy supports more variety of numerical types than native python
- These numerical types are instances of dtype objects, used as np.<_numerical-type_>
- dtype objet provides interpretation of fixed block of memory of array

### Creating dtype object
```python
numpy.dtype(object, align, copy)
```

In [16]:
import numpy as np

In [18]:
# Using array-scalar type
dt = np.dtype(np.int32)
print(dt)

int32


In [21]:
dt = np.dtype('i2')
print(dt)

int16


In [23]:
# Little and big-endian dtypes
dt_le = np.dtype('<i4')
dt_be = np.dtype('>i1')
print(dt_le)
print(dt_be)

int32
int8


In [28]:
# use structured data-type, specifying field name and its data-type
dt_str = np.dtype([('num',np.int8)]) # list of tuple
print(dt_str)
# apply this dtype object to ndarray object
a = np.array([(10,),(20,),(30,)], dtype=dt_str)
print(a)

[('num', 'i1')]
[(10,) (20,) (30,)]


In [30]:
# print age column
print(a['num'])

[10 20 30]


In [32]:
# Structured data type '_student_'
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [36]:
# create ndarray with '_student_' dtype
a = np.array([('Sonya',21,78.9),('Tanya',22,82.1)], dtype=student)
print(a)
print(a['marks'])  # returns '_marks_' column as 1-D ndarray object

[(b'Sonya', 21, 78.9) (b'Tanya', 22, 82.1)]
[78.9 82.1]


## Array attributes
(https://www.tutorialspoint.com/numpy/numpy_array_attributes.htm)
- To get/set attributes of different numpy objects like ndarray, dtype etc.

In [40]:
# ndarray.shape -> returns tuple having array dims. 
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [42]:
# Change shape of ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
# reshape using function
b = a.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [50]:
# ndarray.ndim -> returns number of array dimentions i.e. length of shape tuple
a = np.arange(0,24,2,'i1')
print(a.ndim)
b = a.reshape((2,3,2))
print(b.ndim)

1
3


In [51]:
# ndarray.itemsize -> length of each element of array in bytes
x = np.array([1,2,3,4,5], dtype='i2')
print(x.itemsize)

2


In [56]:
# Itemsize for structure dtype
dt_str = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(dt_str)
a = np.array([('S1',23,88.3),('S2',21,87.4)], dtype=dt_str)
print(a.itemsize)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
25


In [57]:
# ndarray.flags -> list out attributes for ndarray objects
x = np.array([1,2,3,4,5], dtype='i2')
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


## Array Creation
(https://www.tutorialspoint.com/numpy/numpy_array_creation_routines.htm)
- There are several ndarray object creation routines using different constructors.
- Some functions to crate ndarray from scratch
- Some from existing data object/containers

In [1]:
# numpy.empty -> uninitialized array of certain shape and dtype.
# numpy.empty(shape, dtype = float, order = 'C')
import numpy as np
x = np.empty((3,2),dtype='i2')
print(x) # will show some random values

[[  2722 -10371]
 [  2046      0]
 [  2752 -10370]]


In [60]:
# numpy.zeros -> new array of specified size, filled with zeros (0)
# numpy.zeros(shape, dtype = float, order = 'C')
x = np.zeros((2,3),dtype=np.uint16)
print(x)

[[0 0 0]
 [0 0 0]]


In [69]:
# Zero ndarray with custom dtype
x = np.zeros((2,2), dtype = [('x','i2'),('y','f8')])
print(x)

[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]


In [71]:
# numpy.ones -> new array of specified size, filled with ones (1)
# numpy.ones(shape, dtype = float, order = 'C')
x = np.ones((2,2), dtype = [('x','i2'),('y','f8')])
print(x)

[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]


In [13]:
# create nnumpy ndarry from existing python data objects like list, list of lists, tuple, list of tuple, tot etc
x = (1,4,6)
a = np.asarray(x,dtype=np.float)
print(a)

lot = [(1,4,6),(2,3)]
nd_lot = np.asarray(lot)
print(nd_lot)
print(nd_lot.dtype)

[1. 4. 6.]
[(1, 4, 6) (2, 3)]
object


### numpy.frombuffer
any object that exposes buffer interface can be used as pramater to construct ndarray object
```python
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```
__default__ -1 means all data

__offset__ The starting position to read from. Default is 0

In [25]:
s = 'Hello Numpy'
# nd_buf = np.frombuffer(s, dtype='S1')
nd_str = np.fromstring(s, dtype='S1')
# print("nd_buf - {0}".format(nd_buf))
print("nd_str - {0}".format(nd_str))

nd_str - [b'H' b'e' b'l' b'l' b'o' b' ' b'N' b'u' b'm' b'p' b'y']


C:\Users\vishjain\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [27]:
# using iterators
# numpy.fromiter(iterable, dtype, count = -1)
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
nd_itr = np.fromiter(it, dtype = float) 
print(nd_itr)

[0. 1. 2. 3. 4.]


## Ndarray from numerical ranges
(https://www.tutorialspoint.com/numpy/numpy_array_from_numerical_ranges.htm)

1. __numpy.arange__ ->
ndarray object with evenly spaces values within given range.
```python
np.arange(start=0,stop,step=1,dtype)
```
__dtype__ if not given, is taken as that of input


2. __numpy.linspace__ ->
ndarray object where number of evenly spaced values to be generated is provided
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype)
```


3. __numpy.logspace__ ->
ndarray object where number of evenly spaced values, on log scale, to be generated is provided
```python
numpy.logspace(start, stop, num=50, endpoint=True, base=10, dtype)
```

In [32]:
import numpy as np
nd_arange = np.arange(11, step=2, dtype='f2')
print(nd_arange)

[ 0.  2.  4.  6.  8. 10.]


In [38]:
nd_linspace = np.linspace(10,21,6,dtype='f4')
print(nd_linspace)

[10.  12.2 14.4 16.6 18.8 21. ]


In [39]:
nd_linspace = np.linspace(10,21,6,dtype='f4',retstep=True)
print(nd_linspace)

(array([10. , 12.2, 14.4, 16.6, 18.8, 21. ], dtype=float32), 2.2)


In [42]:
nd_logspace = np.logspace(1,10,10,2)
print(nd_logspace)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


# See next notebook for manipulation and processing of numpy ndarrays